### ISSUE TITLE
GraphQL Schema Generation Fails for Locally defined Service Objects

### ISSUE THREAD

**Issue by zetcco** [ballerina-platform/ballerina-library#5925] opened 2024-01-09 12:27 UTC
**Description:**
The current compiler plugin for the GraphQL module generates a schema for module-level defined service objects and service declarations. However, when attempting to run a GraphQL service with locally defined service objects, it fails.

**Steps to reproduce:**
```ballerina
import ballerina/lang.runtime;
import ballerina/graphql;

public function main() returns error? {
    graphql:Service gqlService = service object {
        resource function get greeting() returns string {
            return "Hello, world!";
        }
    };
    graphql:Listener l = check new(9090);
    check l.attach(gqlService, "graphql");
    check l.'start();
    runtime:registerListener(l);
}
```
Running the above service generates the following error.
```
$ bal run ./service.bal
Compiling source
        service.bal

Running executable

error: Error occurred while creating the schema
```

**Comment by DimuthuMadushan** [comment] 2024-01-09 12:40
Duplicate of https://github.com/ballerina-platform/ballerina-library/issues/3317

**Closed by DimuthuMadushan** 2024-01-09 12:40 UTC
Labels: Type/Improvement, module/graphql, Team/PCM
