### ISSUE TITLE
Fix standard library modules for `isolated` object `init` method changes

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-library#4584] opened 2023-06-19 06:26 UTC
**Description:**

We recently identified an in issue in the language that allowed invalid updates of restricted fields within the `init` method of an isolated object.

Currently we don't require using lock statements when accessing restricted fields (using `self`) in the `init` method of an `isolated` object. But while initialization of these fields doesn't require lock statements (requiring an isolated expression as the initial value guarantees that the object will be an isolated root), other kinds of access such as when using a langlib method to update a structure that is set to a restricted field require a lock statement to carry out the relevant transfer in/out analysis (which is associated with a lock statement) to ensure the object is an `isolated` root.

E.g.,
```ballerina
isolated class Class {
    private int[][] arr = [];

    function init(int[] node) {
        // self.arr = [node]; // error
        self.arr = [node.clone()]; // OK

        self.arr.push(node); // allowed at the moment, 
                             // but violates the isolated root invariant
    }

    function fn(int[] node) {
        lock {
            // self.arr.push(node); // error
            self.arr.push(node.clone()); // OK
        }
    }
}

public function main() {
    int[] intArr = [1, 2];

    Class cl = new (intArr);

    // Same mutable array can be accessed via `cl` and `intArr`.
    // Therefore, `cl` is not an `isolated` root, which cannot be the
    // case since `Class` is an `isolated` object.
}
```

Draft PR with initial changes to fix this issue - https://github.com/ballerina-platform/ballerina-lang/pull/40737.

There are multiple stdlib module failures, including
- HTTP 
- gRPC
- GraphQL

Appreciate if these can be fixed. Will share a timestamp for a version with these changes once the PR is merged to the branch.

**Comment by MaryamZi** [comment] 2023-06-20 06:27
ballerina-lang branch - https://github.com/ballerina-platform/ballerina-lang/tree/fix-isolated-in-init

Timestamped snapshot version - 2201.7.0-20230620-082800-c0018aae

**Comment by ThisaruGuruge** [comment] 2023-06-22 04:33
Is this going with Update 7?

**Comment by MaryamZi** [comment] 2023-06-23 04:01
> Is this going with Update 7?

That was the original plan, because it would be better to merge this as soon as possible since it is a breaking change. 

But we need the standard libraries to be fixed, so I guess it would depend on the time taken for that. For example, I'm assuming fixing HTTP may not be straightforward since interceptors are not `isolated`, whereas for some other modules it may be just a change to use `lock` statements.

**Comment by ThisaruGuruge** [comment] 2023-06-23 04:12
The issue is we are past the code freeze and might not have enough time to complete this with Update 7. We can prioritize this for the next sprint aiming at Update 8. Will that be okay?

**Comment by MaryamZi** [comment] 2023-06-23 04:24
> The issue is we are past the code freeze and might not have enough time to complete this with Update 7. We can prioritize this for the next sprint aiming at Update 8. Will that be okay?

Sorry, my bad, I meant next month's release, so Update 8 it is. :)

**Comment by MaryamZi** [comment] 2023-07-18 07:11
Can we get the versions bumped in packages that use these fixed modules too? Levels 6, 7, 8, and 9 are failing in today's build (https://github.com/ballerina-platform/ballerina-lang/pull/40757).

**Comment by TharmiganK** [comment] 2023-07-18 07:13
> Can we get the versions bumped in packages that use these fixed modules too? Levels 6, 7, 8, and 9 are failing in today's build ([ballerina-platform/ballerina-lang#40757](https://github.com/ballerina-platform/ballerina-lang/pull/40757)).

Sure, will do

**Comment by ThisaruGuruge** [comment] 2024-06-07 04:13
Closing the issue as this is now completed.

**Closed by ThisaruGuruge** 2024-06-07 04:13 UTC
Labels: Priority/High, Type/Task, module/http, module/grpc, module/graphql
