### ISSUE TITLE
When generating the client code using the OpenAPI spec an error is printed to the console even though the client generation is successful 

### ISSUE THREAD

**Issue by ayeshLK** [ballerina-platform/ballerina-library#6651] opened 2024-06-24 10:00 UTC
**Description:**
> $subject

When generating the client connector for Slack OpenAPI specification [1] following error is printed in the console, but the client generation was successful. 
```sh
ERROR: Invalid reference found null in the schema.
ERROR: Invalid reference found null in the schema.
ERROR: Invalid reference found null in the schema.
ERROR: Invalid reference found null in the schema.
...
```

Ballerina distribution version:  2201.9.0

[1] - https://api.apis.guru/v2/specs/slack.com/1.7.0/openapi.json

**Comment by TharmiganK** [comment] 2024-07-08 04:34
Duplicate of https://github.com/ballerina-platform/ballerina-library/issues/6698

**Closed by TharmiganK** 2024-07-08 04:34 UTC
Labels: Resolution/Duplicate, Type/Bug, Reason/Other, module/openapi-tools
