### ISSUE TITLE
bal tool is not working when java is not installed 

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-library#6473] opened 2024-04-30 15:58 UTC
**Description:**

Getting the following error when trying to execute the `bal edi` command.  

Note : Java is not installed in this machine. 

```bash
bal edi codegen -i resources/schema.json -o modules/orders/records.bal
Generating code for resources/schema.json...
The operation couldn’t be completed. Unable to locate a Java Runtime.
Please visit http://www.java.com for information on installing Java
```

Observed the error in both 8.5 and 9.0 RC as well.

More details if needed.

<img width="670" alt="image" src="https://github.com/ballerina-platform/ballerina-library/assets/16300038/fc87f939-4310-4f15-af99-0cb4fb80f968">

**Comment by niveathika** [comment] 2024-05-03 02:37
We are able to reproduce this issue. 

To give more context, edi-tool is designed such that the logic can be kept in a ballerina package. The tool runs the compiled jar when invoked. This is the reason for java dependency. To keep the design and remove the dependency, I am looking into if we can pack the bala and run that using Project APIs when  the tool is invoked. 

If the above solution does not work out, we are left with only following options,
1. Report the java dependency in docs so the user does not come into the issue
2. Migrate the logic from ballerina to java. This will be a huge effort.

**Comment by niveathika** [comment] 2024-05-10 08:59
For now I am proposing a workaround by having the user install ballerina instead of java.

https://github.com/ballerina-platform/edi-tools/pull/45

This still needs to be evaluated at architecture level to see if there are different efficient solutions.

**Comment by niveathika** [comment] 2024-05-29 04:36
We have decided to go with using `bal run` instead of `java -jar` to execute the jar. This is a temporary measure till the CLI tool interface is revamped as mentioned in https://github.com/ballerina-platform/ballerina-lang/issues/42729#issuecomment-2136494953

**Comment by niveathika** [comment] 2024-05-29 05:05
The PR will remove the `java` dependency. However, the fix requires that ballerina is installed in the machine. This will be fixed in U10 and will be tracked in https://github.com/ballerina-platform/ballerina-library/issues/6575

**Closed** 2024-05-29 05:05 UTC
Labels: Priority/Blocker, Type/Bug, module/edi
