### ISSUE TITLE
[Bug]: Error while using SQL keyword as table name in persist model

### ISSUE THREAD

**Issue by SasinduDilshara** [ballerina-platform/ballerina-library#4760] opened 2023-08-28 09:47 UTC
Consider the following record that I used inside the persist model for mysql

```
public type Order record {|
    readonly string orderId;
    string customerId;
    Item[] items;
    float totalAmount;
    string shipId;
    string date;
    string eta;
    OrderStatus status;
|};
```

While I doing the `getAll` call for the above model table I get following SQL error

```
Error: Error while executing SQL query: SELECT Order.orderId AS `orderId`,Order.customerId AS `customerId`,Order.totalAmount AS `totalAmount`,Order.shipId AS `shipId`,Order.date AS `date`,Order.eta AS `eta`,Order.status AS `status` FROM Order AS Order. You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'Order AS Order' at line 1.
```

This may be because, order is a keyword of SQL

**Comment by kaneeldias** [comment] 2023-09-04 03:46
This issue was identified in a previous version of `persist.sql` and has been fixed with [this PR](https://github.com/ballerina-platform/module-ballerinax-persist.sql/pull/16)

Updating `persist.sql` to version 1.1.0 or above should work.

**Comment by daneshk** [comment] 2024-01-05 04:04
Closing the issue based on the above comment. Please reopen if the issue is still exists

**Closed by daneshk** 2024-01-05 04:04 UTC
Labels: Type/Bug, module/sql, module/mysql, module/persist
