### ISSUE TITLE
[Bug]: Query parameters are getting parsed

### ISSUE THREAD

**Issue by chathuranga95** [ballerina-platform/ballerina-library#7481] opened 2024-12-19 09:32 UTC
### Description

When a http service is created with ballerina, the query params accepted to the resource functions are getting parsed when they have delimiters.

### Steps to Reproduce

Run the following code with ballerina `2201.5.5` and issue the same request. Observe that the service is logging the query param as the first item in the comma-separated string.

Expected behaviour: The ballerina service should accept the query params as they are.
**Code**
```ballerina
import ballerina/log;
import ballerina/http;

service / on new http:Listener(9091) {
    resource function get greeting(string q) returns string {
        log:printInfo(q);
        return "Hello, World!";
    }
}
```

**Request**
```sh
curl --location 'localhost:9091/greeting?q=1%2C2'
```

**Log output**
```
time = 2024-12-19T14:46:05.119+05:30 level = INFO module = chathurangas/multi_server_debugger message = "1"
```

### Related area

-> Standard Library

**Comment by NipunaRanasinghe** [comment] 2024-12-19 12:02
@chathuranga95 if this a customer related issue, could you please create an issue in the https://github.com/wso2-enterprise/internal-support-ballerina/ repo? That will help us to prioratize the issue

**Comment by TharmiganK** [comment] 2024-12-20 04:19
Tested the same code in Ballerina version - `2201.5.5` and http package version - `2.8.9`, and it is working as expected for the mentioned cURL request(note that the value is a encoded string of value `1,2`):
```console
$ curl --location 'localhost:9091/greeting?q=1%2C2'
Hello, World!
```

Receiving the following log:
```console
$ bal run     
Compiling source
        tharmigan/test:0.1.0

Running executable

time = 2024-12-20T09:44:17.220+05:30 level = INFO module = tharmigan/test message = "1,2"
```

**Comment by TharmiganK** [comment] 2024-12-20 04:20
Closing this issue since it is not reproducible with the latest version

**Closed by TharmiganK** 2024-12-20 04:20 UTC
Labels: Type/Bug, module/http, Team/PCM, Reason/Invalid, Team/StandardLibs
